### ISSUE TITLE
RFE: show image type in jobs overview

### ISSUE THREAD

**Issue by mattdm** [kushaldas/autocloud#19]
Right now, https://apps.fedoraproject.org/autocloud/jobs/ shows IDs and success, but it'd be nice to know if the image is Atomic or Base, which architecture, and which Fedora release it's built on.

It might also be nice to have pre-release images and post-release images highlighted differently (that is, if it's F23 testing branch, or F22 + updates), and Rawhide too, for that matter.

**Comment by rtnpro** [comment]
@sayanchowdhury 

Some links you will find useful:
- https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.buildsys.task.state.change&contains=createImage
- https://apps.fedoraproject.org/datagrepper/id?id=2015-eae5ea8b-76ef-49fd-859e-3a421a8880a8&is_raw=true&size=extra-large
