### ISSUE TITLE
Add an API

### ISSUE THREAD

**Issue by AdamWill** [kushaldas/autocloud#29]
It would be very helpful if autocloud had an API. The only feature I'd immediately need is a very simple one: go to a URL and get the results of the autocloud test for a specific Koji build ID.

So for instance I could go to https://apps.fedoraproject.org/autocloud/api/v1/job/12604897 and get a simple JSON (or whatever) representation of the job; basically it could simply give all the JobDetails attributes except possibly 'output' (which is pretty big). You could obviously implement other end points, like one for listing/querying jobs, but I don't need that right now myself (dunno if anyone else does).

This should be really pretty trivial to implement with flask-restful or flask-restless - I think with flask-restless it'd be like a handful of lines of code. See https://flask-restless.readthedocs.org/en/latest/quickstart.html and https://flask-restful.readthedocs.org/en/latest/quickstart.html .

If you don't have cycles to work on this I can do it, but I think it might be a bit quicker for you if you don't mind :)

**Comment by AdamWill** [comment]
Sorry, now I think about it more clearly, one specific feature request: I'd need to be able to find tests by the Koji task ID (not the autocloud internal test ID). What I want to do is include the autocloud test results in the 'compose check' emails; fedfind can trivially get all the Koji task IDs for a given nightly, so what I need from autocloud is an easy way to say 'tell me the status of your test for Koji task X'.

**Comment by AdamWill** [comment]
So I've looked into this a bit more. Good news, the code is trivial to add a simple API with restless, it's like three lines, I have a patch that ought to work. Not great but OK news, finding tests by Koji task ID will be slightly fiddly as it'll have to use restless' query format since koji task ID isn't a primary key (and can't really be made into one, presumably, as we may have to run the tests for a koji task multiple times if something goes wrong, I guess). Somewhat bad news, the restless package in Fedora is ancient, and recent versions added a dep on something that's not in the Fedora repos. Also there's no restless package for EPEL, which I guess may be an issue if autocloud is running on EL not Fedora.

I'm working through the packaging issues ATM, there's no showstopper, just a bit of yak shaving; I'll have a review request in for `python-mimerender` (the new dep) soon.

**Comment by AdamWill** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1300457 is the `python-mimerender` package review request, if someone wants to do it.

**Comment by AdamWill** [comment]
OK, so I'm more or less done with the yak shaving now :) Updated `python-flask-restless` packages are in updates-testing, and I'll post my PR for adding a simple restless API tomorrow.

**Comment by kushaldas** [comment]
Closing it manually as I added wrong bug number.

**Comment by AdamWill** [comment]
Thanks! How long does it take until the production autocloud instance has this?
